### ISSUE TITLE
Cannot find module ./config

### ISSUE THREAD

**Issue by SlackingVeteran** [IrfaanKhalid/hacker-travel#20]
```
root@LAPTOP-NBLNDV6F:~/trvl# node ./server/index.js
module.js:472
    throw err;
    ^

Error: Cannot find module './config'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/trvl/server/src/car_calculations.js:1:76)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by rsun0** [comment]
We did not push our config.js file to the repo because it contains our API keys from Edmunds API, Google Maps API and Firebase. In order to run it yourself, please get your own API keys and create your own config.js. Use the example-config.js file in trvl/server/src as a template, and save your config.js file in that same directory.

**Comment by SlackingVeteran** [comment]
Okay thanks, it would have been easier if there was any guide about it.

**Comment by bencooper222** [comment]
#21
